export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const PROCESS_COMPLETE = 'PROCESS_COMPLETE';

// account update
export const PASSWORD_CHANGE_COMPLETE = 'PASSWORD_CHANGE_COMPLETE';
export const PASSWORD_CHANGE_ERROR = 'PASSWORD_CHANGE_ERROR';
export const EMAIL_CHANGE_COMPLETE = 'EMAIL_CHANGE_COMPLETE';
export const EMAIL_CHANGE_ERROR = 'EMAIL_CHANGE_ERROR';
export const NAME_CHANGE_COMPLETE = 'NAME_CHANGE_COMPLETE';
export const NAME_CHANGE_ERROR = 'NAME_CHANGE_ERROR';
export const RESET_ACCOUNT_UPDATE = 'RESET_ACCOUNT_UPDATE';

// profile
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const PROFILE_LOADED = 'PROFILE_LOADED';

// location
export const LOCATIONS_LOADING = 'LOCATIONS_LOADING';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const SET_FEATURED_LOCATION = 'SET_FEATURED_LOCATION';

// bookings
export const SET_BOOKING_DATA = 'SET_BOOKING_DATA';
export const GET_BOOKINGS = 'GET_BOOKINGS';
export const GET_UPCOMING_BOOKINGS = 'GET_UPCOMING_BOOKINGS';
export const GET_PAST_BOOKINGS = 'GET_PAST_BOOKINGS';
export const BOOKINGS_LOADING = 'BOOKINGS_LOADING';

// payments
export const GET_PAYMENT = 'GET_PAYMENT';
export const GET_PAYMENTS = 'GET_PAYMENTS';
export const PAYMENT_LOADING = 'PAYMENT_LOADING';

// admin
export const ADMIN_GET_LOCATIONS = 'ADMIN_GET_LOCATIONS';
export const ADMIN_GET_LOCATION = 'ADMIN_GET_LOCATION';
export const ADMIN_EDIT_LOCATION = 'ADMIN_EDIT_LOCATION';
export const ADMIN_GET_BOOKINGS = 'ADMIN_GET_BOOKINGS';
export const ADMIN_GET_USERS = 'ADMIN_GET_USERS';
