export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// profile
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';

// location
export const LOCATIONS_LOADING = 'LOCATIONS_LOADING';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const SET_FEATURED_LOCATION = 'SET_FEATURED_LOCATION';

// bookingS
export const SET_BOOKING_DATA = 'SET_BOOKING_DATA';
export const GET_BOOKINGS = 'GET_BOOKINGS';
export const BOOKINGS_LOADING = 'BOOKINGS_LOADING';
