export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// profile
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';

// location
export const LOCATIONS_LOADING = 'LOCATIONS_LOADING';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const SET_FEATURED_LOCATION = 'SET_FEATURED_LOCATION';
